version: "3"
services:
  backend:
    container_name: budget-tracker-backend
    restart: always
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - tracker_network

  mongo:
    container_name: mongo
    build: ./database
    networks:
      - tracker_network

  frontend:
    container_name: budget-tracker-frontend
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - tracker_network
    depends_on:
      - backend

networks:
  tracker_network:
    driver: bridge
