version: "3"
services:
  backend:
    expose:
      - "3001"
    container_name: budget-tracker-backend
    restart: always
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
  mongo:
    container_name: mongo
    build: ./database
    ports:
      - "27017:27017"
    networks:
      - mern-app

  frontend:
    container_name: budget-tracker-frontend
    restart: always
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
networks:
  mern-app:
    driver: bridge
