version: "3.3"
services:
  backend:
    container_name: budget-tracker-backend
    restart: always
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - budgettrackernetwork

  mongo:
    container_name: mongo
    build: ./database
    networks:
      - budgettrackernetwork

  frontend:
    container_name: budget-tracker-frontend
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - budgettrackernetwork
    depends_on:
      - backend
networks:
  budgettrackernetwork:
    driver: bridge
