version: "3"
services:
  backend:
    container_name: budget-tracker-backend
    restart: always
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    build: ./database
    ports:
      - "27017:27017"
    networks:
      - mern-app

  frontend:
    container_name: budget-tracker-frontend
    stdin_open: true
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - backend
networks:
  mern-app:
    driver: bridge
